### ISSUE TITLE
SD662 support

### ISSUE THREAD

**Issue by Xhelowrk** [Robotix22/edk2-ginkgo#1]
Is support possible on a snapdragon 662 device? And is there a way to contact you, for example, through discord?

**Comment by vicenteicc2008** [comment]
What device?

**Comment by Xhelowrk** [comment]
> What device?

Xiaomi Redmi 9T

**Comment by Robotix22** [comment]
Yes support for Snapdragon 662 is Possible and to contact me over Discord look into one of my EDK2 Ports
